[package]
name = "flamingo"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1"

[target.'cfg(target_os = "android")'.dependencies]
flamingo_rs = { git = "https://github.com/QuestPackageManager/flamingo_rs.git"}

[target.'cfg(not(target_os = "android"))'.dependencies]
retour = "0.4.0-alpha.3"