#![feature(box_patterns, extend_one)]
#![doc(html_root_url = "https://stackdoubleflow.github.io/quest-hook-rs/quest_hook_proc_macros")]
#![warn(
    clippy::all,
    clippy::await_holding_lock,
    clippy::char_lit_as_u8,
    clippy::checked_conversions,
    clippy::dbg_macro,
    clippy::debug_assert_with_mut_call,
    clippy::doc_markdown,
    clippy::empty_enums,
    clippy::enum_glob_use,
    clippy::exit,
    clippy::expl_impl_clone_on_copy,
    clippy::explicit_deref_methods,
    clippy::explicit_into_iter_loop,
    clippy::fallible_impl_from,
    clippy::filter_map_next,
    clippy::float_cmp_const,
    clippy::fn_params_excessive_bools,
    clippy::if_let_mutex,
    clippy::implicit_clone,
    clippy::imprecise_flops,
    clippy::inefficient_to_string,
    clippy::invalid_upcast_comparisons,
    clippy::large_types_passed_by_value,
    clippy::let_unit_value,
    clippy::linkedlist,
    clippy::lossy_float_literal,
    clippy::macro_use_imports,
    clippy::manual_ok_or,
    clippy::map_err_ignore,
    clippy::map_flatten,
    clippy::map_unwrap_or,
    clippy::match_same_arms,
    clippy::match_wildcard_for_single_variants,
    clippy::mem_forget,
    unexpected_cfgs,
    clippy::mut_mut,
    clippy::mutex_integer,
    clippy::needless_borrow,
    clippy::needless_continue,
    clippy::needless_pass_by_value,
    clippy::option_option,
    clippy::path_buf_push_overwrite,
    clippy::ptr_as_ptr,
    clippy::ref_option_ref,
    clippy::rest_pat_in_fully_bound_structs,
    clippy::same_functions_in_if_condition,
    clippy::semicolon_if_nothing_returned,
    clippy::string_add_assign,
    clippy::string_add,
    clippy::string_lit_as_bytes,
    clippy::todo,
    clippy::trait_duplication_in_bounds,
    clippy::unimplemented,
    clippy::unnested_or_patterns,
    clippy::unused_self,
    clippy::use_self,
    clippy::useless_transmute,
    clippy::verbose_file_reads,
    clippy::zero_sized_map_values,
    future_incompatible,
    nonstandard_style,
    rust_2018_idioms,
    missing_docs,
    rustdoc::broken_intra_doc_links,
    rustdoc::private_intra_doc_links
)]

//! Procedural macros for the `quest_hook` crate

mod hook;
mod il2cpp_functions;
mod impl_arguments_parameters;
mod impl_generics;
mod impl_type;

use std::num::NonZeroUsize;
use std::ops::Range;

use proc_macro::TokenStream;
use syn::parse::{Parse, ParseStream};
use syn::spanned::Spanned;
use syn::{parse_macro_input, Error, Expr, ExprLit, ExprRange, ItemFn, Lit, RangeLimits, Result};

/// Creates an inline hook at a C# method.
///
/// The method to hook is given one of two mutually exclusive ways:
///
/// * Explicitly, as the namespace, class name, and method name of the C# method
///   to hook: `#[hook("Namespace", "Class", "Method")]`.
/// * As a path to a real method on a class, e.g. one generated by a codegen
///   tool derived from an il2cpp dump: `#[hook(SceneManager::SetActiveScene)]`.
///   `SceneManager` (every segment but the last) must implement
///   `quest_hook::libil2cpp::Type`, which supplies the namespace/class name;
///   the last segment's text (`SetActiveScene`) is the method name. This hook's
///   declared `this`/parameter/return types are then checked against
///   `SceneManager::SetActiveScene`'s real signature at compile time - a
///   mismatch is a compile error naming both signatures directly, not a runtime
///   one. This does not fill in or change the types the hook declares; they
///   must still be written out in full.
///
/// Either form may be followed by any of these optional `key = "value"`
/// arguments:
///
/// * `namespace`: overrides the hook's own namespace (used to reference it from
///   another hook's `before`/`after`), which otherwise defaults to the crate
///   name. The hook's own name always defaults to the name of the function it
///   wraps.
/// * `before` / `after`: installs this hook so it runs before/after every
///   already-installed hook matching a filter, in one of the forms `"name"`
///   (any namespace), `"namespace::"` (any name), or `"namespace::name"`. May
///   be repeated (including a mix of `before` and `after`) to add more
///   constraints. Only meaningfully enforced by backends that support multiple
///   hooks per target (currently `flamingo`).
///
/// # Panics
///
/// * `original` will panic if the hook has not yet been installed.
#[proc_macro_attribute]
pub fn hook(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as hook::HookArgs);
    let input = parse_macro_input!(item as ItemFn);

    match hook::expand(&args, input) {
        Ok(ts) => ts,
        Err(err) => err.to_compile_error().into(),
    }
}

/// Implements the `Type` trait for a Rust type that is equivalent to a C#
/// reference type
///
/// Note that in order to use this macros, the `generic_associated_types`
/// feature must be enabled.
///
/// The Rust type can optionally name the field holding its `Il2CppObject`
/// header right after the type, separated by a `.` (e.g. `for
/// GameObject.object`). When given, that field is used to implement
/// `Deref`/`DerefMut` to `Il2CppObject`, which in turn is what makes the type
/// pick up the blanket `RefType`/`ObjectExt` impls (giving it
/// `as_object`/`as_object_mut`/`new`, and autoderef access to
/// `Il2CppObject`'s own methods like `invoke`) for free. Leave it off for
/// reference types that aren't a plain struct with an `Il2CppObject` field -
/// e.g. ones that provide `Deref`/`DerefMut` some other way - and implement
/// `RefType` (or the traits it's derived from) by hand instead.
///
/// # Safety
///
/// The type must hold the guarantees required by the `Type` trait.
///
/// # Examples
///
/// The basic syntax follows the pattern `in <libil2cpp path> for <Rust type>
/// [.<object field>] => <C# type>`.
///
/// ```ignore
/// #![feature(generic_associated_types)]
///
/// use libil2cpp::Il2CppObject;
///
/// #[repr(C)]
/// struct GameObject {
///     object: Il2CppObject,
/// }
///
/// unsafe_impl_reference_type!(in libil2cpp for GameObject.object => UnityEngine.GameObject);
/// ```
///
/// It's also possible to use this macro with generic types. In this scenario,
/// the `once_cell` feature must also be enabled.
///
/// ```ignore
/// #![feature(generic_associated_types, once_cell)]
///
/// use libil2cpp::{Il2CppArray, Il2CppObject, Type};
///
/// #[repr(C)]
/// struct List<T: Type> {
///     object: Il2CppObject,
///     items: *mut Il2CppArray<T>,
///     size: i32,
/// }
///
/// unsafe_impl_reference_type!(in libil2cpp for List<T>.object => System.Collections.Generic.List<T>);
/// ```
///
/// A class getter can be provided manually.
///
/// ```ignore
/// #![feature(generic_associated_types)]
///
/// use libil2cpp::Il2CppObject;
///
/// #[repr(C)]
/// struct MyClass {
///     object: Il2CppObject,
/// }
///
/// unsafe_impl_reference_type!(in libil2cpp for MyClass.object => MyNamespace.MyClass {
///     my_class_getter()
/// });
///
/// # fn my_class_getter() -> &'static libil2cpp::Il2CppClass { unimplemented!() }
/// ```
///
/// Finally, the namespace and class name can be provided as string literals. In
/// this case, the macro will no change them in any way regardless of generic
/// parameters.
///
/// ```ignore
/// #![feature(generic_associated_types, once_cell)]
///
/// use libil2cpp::{Il2CppArray, Il2CppObject, Type};
///
/// #[repr(C)]
/// struct List<T: Type> {
///     object: Il2CppObject,
///     items: *mut Il2CppArray<T>,
///     size: i32,
/// }
///
/// unsafe_impl_reference_type!(in libil2cpp for List<T>.object => "System.Collections.Generic"."List`1"<T>);
/// ```
#[proc_macro]
pub fn unsafe_impl_reference_type(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as impl_type::Input);
    impl_type::expand(&input, impl_type::Semantics::Reference)
}

/// Implements the `Type` trait for a Rust type that is equivalent to a C# value
/// type
///
/// Note that in order to use this macros, the `generic_associated_types` and
/// `once_cell` features must be enabled.
///
/// This macro works the same way as [`unsafe_impl_reference_type!`], except
/// that it is meant for value types, never takes an object field name (value
/// types have no `Il2CppObject` header), and implements some extra traits
/// not covered by blanket impls.
///
/// # Safety
///
/// The type must hold the guarantees required by the `Type` trait.
///
/// # Examples
///
/// The basic syntax follows the pattern `in <libil2cpp path> for <Rust type> =>
/// <C# type>`.
///
/// ```ignore
/// #![feature(generic_associated_types)]
///
/// #[repr(C)]
/// struct Vector3 {
///     x: f32,
///     y: f32,
///     z: f32,
/// }
///
/// unsafe_impl_value_type!(in libil2cpp for Vector3 => UnityEngine.Vector3);
/// ```
#[proc_macro]
pub fn unsafe_impl_value_type(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as impl_type::Input);
    impl_type::expand(&input, impl_type::Semantics::Value)
}

/// Generates bindings for il2cpp functions
///
/// The functions will be dynamically loaded from il2cpp dynamic at runtime.
/// Each function will be wrapped in a safe Rust function that handles loading
/// the symbol on first use.
/// The symbol names are generated by prefixing the function name with
/// `il2cpp_`.
///
/// Example usage:
/// ```ignore
/// il2cpp_functions! { "path/to/libil2cpp.so" =>
///     pub fn domain_get() -> &'static Il2CppDomain;
/// }
/// ```
#[proc_macro]
#[doc(hidden)]
pub fn il2cpp_functions(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as il2cpp_functions::Input);
    match il2cpp_functions::expand(&input) {
        Ok(ts) => ts,
        Err(err) => err.to_compile_error().into(),
    }
}

#[proc_macro]
#[doc(hidden)]
pub fn impl_arguments_parameters(input: TokenStream) -> TokenStream {
    let range = parse_macro_input!(input as RangeInput);
    match impl_arguments_parameters::expand(range.0) {
        Ok(ts) => ts,
        Err(err) => err.to_compile_error().into(),
    }
}

#[proc_macro]
#[doc(hidden)]
pub fn impl_generics(input: TokenStream) -> TokenStream {
    let range = parse_macro_input!(input as RangeInput);
    match impl_generics::expand(range.0) {
        Ok(ts) => ts,
        Err(err) => err.to_compile_error().into(),
    }
}

#[proc_macro_attribute]
#[doc(hidden)]
pub fn identity(_: TokenStream, input: TokenStream) -> TokenStream {
    input
}

struct RangeInput(Range<usize>);

impl Parse for RangeInput {
    fn parse(input: ParseStream<'_>) -> Result<Self> {
        let range: ExprRange = input.parse()?;
        let span = range.span();

        let start = range
            .start
            .ok_or_else(|| Error::new(span, "tuple length range must have a lower bound"))?;
        let start = parse_range_bound(*start)?;

        let end = range
            .end
            .ok_or_else(|| Error::new(span, "tuple length range must have an upper bound"))?;
        let end = parse_range_bound(*end)?;

        let range = match range.limits {
            RangeLimits::HalfOpen(_) if end <= start => {
                return Err(Error::new(span, "tuple length range must be valid"))
            }
            RangeLimits::HalfOpen(_) => start..end,

            RangeLimits::Closed(_) if end < start => {
                return Err(Error::new(span, "tuple length range must be valid"))
            }
            RangeLimits::Closed(_) => start..(end + 1),
        };
        Ok(Self(range))
    }
}

fn parse_range_bound(bound: Expr) -> Result<usize> {
    let bound: NonZeroUsize = match bound {
        Expr::Lit(ExprLit {
            lit: Lit::Int(n), ..
        }) => n.base10_parse()?,
        _ => {
            return Err(Error::new(
                bound.span(),
                "tuple length bound must be an integer",
            ))
        }
    };
    Ok(bound.get())
}
