[package]
name = "libil2cpp"
version = "0.1.0"
authors = [
    "StackDoubleFlow <ojaslandge@gmail.com>",
    "Raphaël Thériault <self@raftar.io>",
]
repository = "https://github.com/StackDoubleFlow/quest-hook-rs.git"
license = "MIT"
edition = "2024"

[dependencies]
quest_hook_proc_macros = { path = "../proc_macros" }
libloading = "0.9"
thiserror = "2"
paste = "1"
serde = { version = "1", optional = true }
bad64 = { version = "0.12.0", optional = true }

[dependencies.tracing]
version = "0.1"
features = ["std", "attributes"]
default-features = false
optional = true

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
libc = { version = "0.2", optional = true }

[features]
default = []
il2cpp_v31 = []
il2cpp_v29 = []
il2cpp_v24 = []
unity2018 = []
# whether to use bindgen to generate bindings at build time
bindgen = ["dep:bindgen", "dep:quest_build_helper"]
cache = []
trace = ["tracing"]

xref = ["dep:bad64", "dep:libc"]

[build-dependencies]
bindgen = { version = "0.72", optional = true }
quest_build_helper = { path = "../quest_build_helper", optional = true }
