use libil2cpp::{Parameters, Return, ThisParameter};

/// Trait implemented by all hooks to facilitate generic programming
/// 
/// Implementation is usually generated by the `#[hook]` macro
pub trait Hook {
    /// Type of this for the hooked method
    type This: ThisParameter;
    /// Type of the parameters for the hooked method
    type Parameters: Parameters;
    /// Type of the return for the hooked method
    type Return: Return;

    /// Namespace of the hooked method's class
    const NAMESPACE: &'static str;
    /// Name of the hooked method's class
    const CLASS_NAME: &'static str;
    /// Name of the hooked method
    const METHOD_NAME: &'static str;
    /// Namespace the hook itself was declared under, defaulting to its
    /// crate name. Used to reference this hook from another hook's `before`
    /// or `after` priority
    const HOOK_NAMESPACE: &'static str;
    /// Name of the hook itself, defaulting to the name of the function it
    /// wraps. Used to reference this hook from another hook's `before` or
    /// `after` priority
    const HOOK_NAME: &'static str;

    /// Installs the hook, returning a handle that can later uninstall it
    /// independently of any other hooks sharing its target
    fn install(&self) -> Result<HookHandle, HookInstallError>;

    /// This hook's declared `before`/`after` priority
    fn priority(&self) -> crate::hook_backend::Priority;

    /// Pointer to the hook function
    fn hook(&self) -> *const ();
    /// Pointer to the hooked method, if installed
    fn original(&self) -> Option<*const ()>;
}

/// Possible errors when installing a hook
#[derive(Debug, thiserror::Error, Clone, Copy, PartialEq, Eq, Hash)]
pub enum HookInstallError {
    /// Hook already installed
    #[error("hook already installed")]
    AlreadyInstalled,

    /// Class not found
    #[error("class not found")]
    ClassNotFound,

    /// Method not found
    #[error("method not found")]
    MethodNotFound,

    /// Error installing hook
    #[error("error installing hook")]
    InstallError,
}

/// A handle to an installed hook, returned by its `install` method, allowing
/// it to be uninstalled independently of any other hooks sharing its
/// target.
///
/// Whether uninstalling actually removes the hook (as opposed to always
/// failing) depends on the active [`hook_backend`](crate::hook_backend)
/// backend; only `flamingo` currently supports it.
pub struct HookHandle {
    hook: &'static crate::hook_backend::FunctionHook,
}

impl HookHandle {
    /// Constructs a handle wrapping `hook`. Only meant to be called by code
    /// generated by the `#[hook]` macro.
    #[doc(hidden)]
    pub fn new(hook: &'static crate::hook_backend::FunctionHook) -> Self {
        Self { hook }
    }

    /// Uninstalls the hook.
    pub fn uninstall(self) -> Result<(), crate::hook_backend::UninstallError> {
        // SAFETY: `hook` was successfully installed by the generated
        // `install` method, which required `Hook::install`'s safety
        // contract to hold for the lifetime of the process.
        unsafe { self.hook.uninstall() }
    }
}
